feature:
  - "feature/*"
  - "enhancement/*"

bug:
  - "bugfix/*"
  - "fix/*"
  - "hotfix/*"

release:
  - "release/*"

dependency-updates:
  - "updates/*"
  - "renovate/*"

ci-cd:
  - "automation/*"
  - "cicd/*"

documentation:
  - "documentation/*"
  - "doc/*"
