[versions]
ksp = "2.1.10-1.0.30"
kapt = "2.1.10"
agp = "8.8.1"
kotlin = "2.1.10"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
lifecycle = "2.8.7"
navigation = "2.8.7"

#Compose
composeBom = "2025.02.00"
androidxComposeCompiler = "1.7.8"
activityCompose = "1.10.0"

androidTools = "31.8.1"

#Coroutines
coroutines = "1.10.1"
#Hilt
androidxHiltNavigationCompose = "1.2.0"
hiltVersion = "2.55"
#Timber
timber = "5.0.1"
#Swipe to refresh
swipeToRefresh = "1.1.0"
gradle = "8.8.2"
#Google Services
googleServicesVersion = "4.4.2"
#Firebase Crashlytics
firebaseCrashlytics = "19.4.0"
firebaseCrashlyticsGradle = "3.0.3"
#Firebase BoM
firebaseBom = "33.9.0"
#Firebase Performance
firebasePerf = "21.0.4"
perfPlugin = "1.4.2"
#Firebase Firestore
firebaseFirestore = "25.1.2"
#Firebase Storage
firebaseStorage = "21.0.1"
#Shimmer loading
shimmer = "0.5.0"
#Jsoup Web Scraping Library
jsoup = "1.18.3"
#Glide
glide = "4.16.0"
#Room Local SQLite db
room = "2.6.1"
#Circle ImageView
circleImgView = "3.1.0"
#DataStore local storage
dataStore = "1.1.2"
#Paging3
paging = "3.3.6"
#Gson
gson = "2.12.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
fragment-navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
ui-navigation = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

#Delete after compose migration
viewModelLifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
liveDataLifecycle = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }

#AndroidX
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

#Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-compiler = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxComposeCompiler" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }
swipeToRefresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeToRefresh" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
paging = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }

#Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebasePerf" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServicesVersion" }
perf-plugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "perfPlugin" }
circleImgView = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleImgView" }
dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Dependencies of the included build-logic
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "perfPlugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServicesVersion" }
room = { id = "androidx.room", version.ref = "room" }

#Custom Elmepa Plugins
elmepa-android-app = { id = "elmepa.android.application", version = "unspecified" }
elmepa-android-library = { id = "elmepa.android.library", version = "unspecified" }
elmepa-android-compose = { id = "elmepa.android.compose", version = "unspecified" }
elmepa-android-hilt = { id = "elmepa.android.hilt", version = "unspecified" }
elmepa-android-room = { id = "elmepa.android.room", version = "unspecified" }
elmepa-android-feature = { id = "elmepa.android.feature", version = "unspecified" }
