[versions]
ksp = "2.0.0-1.0.22"
kapt = "2.0.0"
agp = "8.8.0"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
lifecycle = "2.8.7"
navigation = "2.8.6"
#Coroutines
coroutines = "1.8.1"
#Hilt
hiltVersion = "2.55"
#Timber
timber = "5.0.1"
#Swipe to refresh
swipeToRefresh = "1.1.0"
gradle = "8.8.0"
#Google Services
googleServicesVersion = "4.4.2"
#Firebase Crashlytics
firebaseCrashlytics = "19.4.0"
firebaseCrashlyticsGradle = "3.0.3"
#Firebase BoM
firebaseBom = "33.9.0"
#Firebase Performance
firebasePerf = "21.0.4"
perfPlugin = "1.4.2"
#Firebase Firestore
firebaseFirestore = "25.1.2"
#Firebase Storage
firebaseStorage = "21.0.1"
#Shimmer loading
shimmer = "0.5.0"
#Jsoup Web Scraping Library
jsoup = "1.18.3"
#Glide
glide = "4.16.0"
#Room Local SQLite db
room = "2.6.1"
#Circle ImageView
circleImgView = "3.1.0"
#DataStore local storage
dataStore = "1.1.2"
#Paging3
paging = "3.3.5"
#Gson
gson = "2.12.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
fragment-navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
ui-navigation = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
viewModelLifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
liveDataLifecycle = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }
swipeToRefresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeToRefresh" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
paging = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebasePerf" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServicesVersion" }
perf-plugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "perfPlugin" }
circleImgView = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleImgView" }
dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "perfPlugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServicesVersion" }