name: Auto Label PR Based on Branch Name

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  pr-automations:
    runs-on: ubuntu-latest
    steps:
      # Add assignee to PR
      - name: Auto assign PR to PR creator
        if: startsWith(github.head_ref, 'renovate/') == false
        run: gh pr edit "$PR_URL" --add-assignee "$GITHUB_ACTOR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      ## Apply labels based on branch name
      - name: Apply labels based on branch name
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const branchName = pr.head.ref;  // Get the PR's branch name
            const labelsToAdd = [];

            // Apply labels based on branch name
            if (branchName.startsWith("feature/") || branchName.startsWith("enhancement/")) {
              labelsToAdd.push("enhancement");
            } else if (branchName.startsWith("fix/") || branchName.startsWith("bugfix/") || branchName.startsWith("bug/")) {
              labelsToAdd.push("bugfix");
            } else if (branchName.startsWith("platform/")) {
              labelsToAdd.push("platform");
            }

            // Apply labels if any are found
            if (labelsToAdd.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: labelsToAdd
              });
            }
